
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.awt.event.*;

    public class StudentInfoApp  extends javax.swing.JFrame {
    private JTextField txtName, txtBirth, txtHometown;
    private JTable table;
    private DefaultTableModel tableModel;
   
    public StudentInfoApp () {
        setTitle("Thông tin sinh viên");
        setSize(600, 400);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLocationRelativeTo(null);
        setLayout(new BorderLayout());

        // Panel nhập liệu
        JPanel inputPanel = new JPanel(new GridLayout(4, 2, 10, 10));

        inputPanel.add(new JLabel("Họ và tên:"));
        txtName = new JTextField();
        inputPanel.add(txtName);

        inputPanel.add(new JLabel("Ngày sinh:"));
        txtBirth = new JTextField();
        inputPanel.add(txtBirth);

        inputPanel.add(new JLabel("Quê quán:"));
        txtHometown = new JTextField();
        inputPanel.add(txtHometown);

        JButton btnAdd = new JButton("Thêm vào bảng");
        inputPanel.add(btnAdd);

        // Chèn panel vào top
        add(inputPanel, BorderLayout.NORTH);

        // Bảng hiển thị
        String[] columnNames = {"Họ và tên", "Ngày sinh", "Quê quán"};
        tableModel = new DefaultTableModel(columnNames, 0);
        table = new JTable(tableModel);

        add(new JScrollPane(table), BorderLayout.CENTER);

        // Sự kiện khi bấm nút
        btnAdd.addActionListener(e -> {
            String name = txtName.getText();
            String birth = txtBirth.getText();
            String hometown = txtHometown.getText();

            // Thêm dòng vào bảng
            tableModel.addRow(new Object[]{name, birth, hometown});

            // Xóa nội dung ô nhập
            txtName.setText("");
            txtBirth.setText("");
            txtHometown.setText("");
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 576, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 383, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       SwingUtilities.invokeLater(() -> new StudentInfoApp().setVisible(true));
    }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

