
import javax.swing.*;

public class SplitPaneApp extends javax.swing.JFrame {

 
    public SplitPaneApp() {
        setTitle("JSplitPane Example");
        setSize(600, 400);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

        //Tao list ben trai
        String[] items = {"Item 1", "Item 2", "Item 3", "Item 4"};
        JList<String> itemList = new JList<>(items);
        JScrollPane listScrollPane = new JScrollPane(itemList);

        // tao JTextArea bên phai
        JTextArea textArea = new JTextArea();
        JScrollPane textScrollPane = new JScrollPane(textArea);

        // Tao JSplitPane chia ngang
        JSplitPane splitPane = new JSplitPane(JSplitPane.HORIZONTAL_SPLIT, listScrollPane, textScrollPane);
        splitPane.setDividerLocation(200); // chia mac dinh 200 pixel
        splitPane.setContinuousLayout(true);

        add(splitPane); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 447, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 328, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
         SwingUtilities.invokeLater(() -> {
            new SplitPaneApp().setVisible(true);
        });
    }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
